### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by milanpanin** [CTNicholas/liveblocks-parallel-routes#1]
This example looks very interesting, I follow the instructions to run the application, but every time I click on some of documents in dashboard I get a runtime error.

![Capture](https://user-images.githubusercontent.com/30274846/231622864-ab783743-681c-4e4a-8554-54b2aa5fd100.PNG)

**Comment by CTNicholas** [comment]
Hi @milanpanin, [this is a Next.js bug](https://github.com/vercel/next.js/pull/48152), and I think it's been fixed now. Try upgrading `next` to `13.3.1-canary.6` in `package.json` to see a canary version with the bug fix.

**Comment by milanpanin** [comment]
It worked! Thanks and kudos for the example, it's great :slightly_smiling_face:
